name: .NET Build and Upload Artifacts

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Add NuGet sources
      run: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --nologo --configuration Release Lilia --output app/
    - name: Test
      run: dotnet test --no-build --nologo --verbosity normal --configuration Release
    - name: Create archive of built files
      run: zip -r -j out.zip /home/runner/work/Lilia/Lilia/app
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: test-release
        release_name: Release test
        prerelease: true
    - name: Upload release assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: /home/runner/work/Lilia/Lilia/out.zip
        asset_name: out.zip
        asset_content_type: application/zip