name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --nologo

      - name: Test
        run: dotnet test --no-build --no-restore --nologo -v n

      - name: Create artifacts (Windows)
        run: |
          dotnet build Lilia -a x86 -c Release --no-self-contained --nologo --output Build/Win_x86
          dotnet build Lilia -a x64 -c Release --no-self-contained --nologo --output Build/Win_x64

      - name: Create artifacts (Mac)
        run: |
          dotnet build Lilia --os osx -a x64 -c Release --no-self-contained --nologo --output Build/Mac_x64

      - name: Create artifacts (Linux)
        run: |
          dotnet build Lilia --os linux -a x64 -c Release --no-self-contained --nologo --output Build/Linux_x64

      - name: Package the build files
        run: |
          sudo apt-get install zip
          zip -r Build.zip Build

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "head"
          prerelease: true
          title: "Build for Windows, Mac & Linux - latest commit"
          files: Build.zip
