name: .NET Build and Upload Artifacts

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Add NuGet sources
      run: dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --nologo --configuration Release Lilia --output app/
    - name: Test
      run: dotnet test --no-build --nologo --verbosity normal --configuration Release
    - name: Create built artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: /home/runner/work/Lilia/Lilia/app
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifact.zip,config.example.json"
        token: ${{ secrets.GITHUB_TOKEN }}
      