name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore package
        run: |
          dotnet nuget add source https://nuget.emzi0767.com/api/v3/index.json
          dotnet restore
      - name: Build and Test
        run: |
          dotnet build --no-restore --nologo
          dotnet test --no-build --no-restore --nologo